"""The manuscript's convention for GC/MFE-deviation-from-natural is the MEAN
OF PER-SEQUENCE ABSOLUTE DIFFERENCES (mean(|gc_i - natural_gc_i|)), computed
per matched protein, exactly as evaluate.py's evaluate_sequence() does for
MitoSeqGen and the four baselines. A quick delta-of-means estimate
(|mean(gc) - mean(natural_gc)|) is NOT the same statistic (mean-of-abs-diffs
>= abs-diff-of-means in general, by the triangle inequality / Jensen's
inequality) and would silently understate the true deviation if used as a
stand-in. This script computes the correct, consistent per-sequence-paired
statistic for the fine-tuned CodonTransformer ablation, so its row in Table 1
is computed the same way as every other row, not approximated.

codontransformer_finetuned_results.json and codontransformer_real_results_full.json
were both generated by `for n, idx in enumerate(test_idx, 1)` (sequential,
unshuffled) iteration order, so they -- and the natural sequences pulled here
by the same iteration -- are already correctly aligned index-by-index; no id
matching is needed.
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.evaluation.metrics import compute_mfe, gc_content

with open(ROOT / "data" / "processed" / "mito_cds_tokenized.json") as f:
    records = json.load(f)["records"]
with open(ROOT / "data" / "splits" / "test.json") as f:
    test_idx = json.load(f)["indices"]
with open(ROOT / "data" / "qc_reports" / "codontransformer_finetuned_results.json") as f:
    ftc = json.load(f)

assert len(ftc) == len(test_idx), f"length mismatch: {len(ftc)} vs {len(test_idx)}"

gc_deltas, mfe_deltas = [], []
for i, idx in enumerate(test_idx):
    rec = records[idx]
    assert rec["id"] == ftc[i]["id"], f"order mismatch at {i}: {rec['id']} vs {ftc[i]['id']}"
    nat_gc = gc_content(rec["sequence"])
    nat_mfe = compute_mfe(rec["sequence"])
    gc_deltas.append(abs(ftc[i]["gc_content"] - nat_gc))
    mfe_deltas.append(abs(ftc[i]["mfe"] - nat_mfe))
    if (i + 1) % 500 == 0:
        print(f"{i+1}/{len(test_idx)} done", flush=True)

mean_gc_delta = sum(gc_deltas) / len(gc_deltas)
mean_mfe_delta = sum(mfe_deltas) / len(mfe_deltas)
print(f"mean_gc_delta_from_natural (per-sequence-paired) = {mean_gc_delta:.4f}")
print(f"mean_mfe_delta_from_natural (per-sequence-paired) = {mean_mfe_delta:.4f}")

with open(ROOT / "data" / "qc_reports" / "codontransformer_finetuned_deltas.json", "w") as f:
    json.dump({
        "mean_gc_delta_from_natural": mean_gc_delta,
        "mean_mfe_delta_from_natural": mean_mfe_delta,
        "gc_deltas": gc_deltas, "mfe_deltas": mfe_deltas,
    }, f)
print("DELTAS COMPUTE COMPLETE")
